export const WORLD_OVERVIEW = `在魔奇獸的世界裡，旅者必須藉由探索古老遺跡與野外秘境，
馴化各地的魔奇獸，讓魔法球吸收能量才能開啟新的冒險章節。`;

export const MAGIC_ORB_TIERS = [
  {
    level: 1,
    name: '初始魔法球',
    maxEnergy: 5,
    description: '蘊含第一道曙光的魔法球，能感應自然界最溫馴的魔奇獸。',
  },
  {
    level: 2,
    name: '星巡魔法球',
    maxEnergy: 7,
    description: '在星光指引下進化的魔法球，可捕捉擅於操控元素的魔奇獸。',
  },
  {
    level: 3,
    name: '極耀魔法球',
    maxEnergy: 9,
    description: '由三張冒險地圖的能量共鳴而成，能封印最古老的守護者。',
  },
];

export const MAGICAL_BEASTS = [
  {
    id: 'glimmer-fox',
    name: '微光狐',
    element: '光',
    habitat: '晨曦森林',
    description: '毛皮散發微光，能在黎明時分引領旅者前往安全的小徑。',
    signatureMove: '晨星閃耀',
  },
  {
    id: 'mossback-tortoise',
    name: '苔背龜',
    element: '木',
    habitat: '苔蘚溪谷',
    description: '背甲覆滿淨化苔蘚，能治癒同伴的疲憊。',
    signatureMove: '綠影守護',
  },
  {
    id: 'ember-wing',
    name: '燼羽鳥',
    element: '火',
    habitat: '餘燼峽谷',
    description: '羽翼藏著古老火種，可以點燃儀式的聖火。',
    signatureMove: '烈羽迴旋',
  },
  {
    id: 'mist-otter',
    name: '霧漾獺',
    element: '水',
    habitat: '雲霧河道',
    description: '吐出的霧氣能為旅伴遮蔽視線，躲避危險。',
    signatureMove: '水霧護罩',
  },
  {
    id: 'thunder-stag',
    name: '雷角鹿',
    element: '雷',
    habitat: '雷鳴高地',
    description: '鹿角吸附雷霆能量，奔馳時能釋放電光。',
    signatureMove: '奔雷衝擊',
  },
  {
    id: 'petal-wisp',
    name: '花絮精靈',
    element: '風',
    habitat: '花穗平原',
    description: '由春季花粉凝聚成形，善於操控空氣流動。',
    signatureMove: '花舞氣旋',
  },
  {
    id: 'frostfang-wolf',
    name: '霜牙狼',
    element: '冰',
    habitat: '寒霜斷崖',
    description: '牙齒能凝結冰晶，讓敵人動作遲緩。',
    signatureMove: '霜牙咬擊',
  },
  {
    id: 'quartz-guardian',
    name: '晶盾兵',
    element: '土',
    habitat: '晶礦洞窟',
    description: '能變換晶盾形態抵擋攻擊，是守護遺跡的天然衛士。',
    signatureMove: '地脈屏障',
  },
  {
    id: 'lumen-koi',
    name: '流光鯉',
    element: '光',
    habitat: '月影湖',
    description: '身鱗如水面星光，能在黑夜照亮湖畔。',
    signatureMove: '星流護波',
  },
  {
    id: 'ashen-jaguar',
    name: '灰燼豹',
    element: '火',
    habitat: '熔炎盆地',
    description: '融入火山灰塵之中的敏捷獵手。',
    signatureMove: '焰影突襲',
  },
  {
    id: 'gale-kirin',
    name: '颶風麒麟',
    element: '風',
    habitat: '流風山嶺',
    description: '腳步輕盈，能召喚狂風驅散雲霧。',
    signatureMove: '天外颶吼',
  },
  {
    id: 'tidal-leviathan',
    name: '潮汐巨靈',
    element: '水',
    habitat: '深潮裂谷',
    description: '以海嘯之力守護遠古的沉沒都市。',
    signatureMove: '潮握深淵',
  },
  {
    id: 'aurora-sphinx',
    name: '極光斯芬克斯',
    element: '光',
    habitat: '極光祭壇',
    description: '以謎語考驗旅者，被尊為北境守護者。',
    signatureMove: '曙光審判',
  },
  {
    id: 'obsidian-drake',
    name: '黑曜龍',
    element: '暗',
    habitat: '黑曜裂隙',
    description: '身披黑曜石鱗片，能吞噬光芒化為力量。',
    signatureMove: '深淵之翼',
  },
  {
    id: 'mythic-phoenix',
    name: '神話鳳凰',
    element: '火',
    habitat: '星火王座',
    description: '傳說最後的王者，從灰燼中重生，擁有治癒與破壞的雙重力量。',
    signatureMove: '永焰新生',
  },
];

export const ADVENTURE_MAPS = [
  {
    id: 'aurora-wilds',
    name: '晨曦原野',
    orbLevelRequired: 1,
    environment: '林地與溪谷',
    summary: '一切旅程的起點，晨光灑落的原野蘊藏自然的守護者。',
    chapters: [
      {
        id: 'aurora-1',
        name: '黎明的呼喚',
        description: '追尋失落的星羽，尋找最初的魔奇獸。',
        boss: '微光狐',
        rewardBeastId: 'glimmer-fox',
      },
      {
        id: 'aurora-2',
        name: '苔蘚溪谷試煉',
        description: '順著溪流穿越，被苔背龜守護的療癒之地。',
        boss: '苔背龜',
        rewardBeastId: 'mossback-tortoise',
      },
      {
        id: 'aurora-3',
        name: '餘燼之風',
        description: '對抗餘燼峽谷的火舌，解放燼羽鳥。',
        boss: '燼羽鳥',
        rewardBeastId: 'ember-wing',
      },
      {
        id: 'aurora-4',
        name: '雲霧之謎',
        description: '破解雲霧河道中的迷霧，馴服霧漾獺。',
        boss: '霧漾獺',
        rewardBeastId: 'mist-otter',
      },
      {
        id: 'aurora-5',
        name: '雷鳴終章',
        description: '與雷角鹿進行最後對決，點亮魔法球。',
        boss: '雷角鹿',
        rewardBeastId: 'thunder-stag',
      },
    ],
  },
  {
    id: 'tempest-archipelago',
    name: '風暴群島',
    orbLevelRequired: 2,
    environment: '群島與天空之路',
    summary: '星巡魔法球解鎖後才能抵達的天空浮島，風暴與潮汐交錯。',
    chapters: [
      {
        id: 'tempest-1',
        name: '花穗風暴',
        description: '與花絮精靈一同平息擴散的花暴。',
        boss: '花絮精靈',
        rewardBeastId: 'petal-wisp',
      },
      {
        id: 'tempest-2',
        name: '寒霜斷崖',
        description: '攀上寒霜斷崖，解放被冰封的霜牙狼。',
        boss: '霜牙狼',
        rewardBeastId: 'frostfang-wolf',
      },
      {
        id: 'tempest-3',
        name: '晶礦防衛戰',
        description: '協助晶盾兵抵擋入侵的影獸。',
        boss: '晶盾兵',
        rewardBeastId: 'quartz-guardian',
      },
      {
        id: 'tempest-4',
        name: '月影湖心',
        description: '傾聽流光鯉的歌聲，獲得夜航的祝福。',
        boss: '流光鯉',
        rewardBeastId: 'lumen-koi',
      },
      {
        id: 'tempest-5',
        name: '熔炎審判',
        description: '面對灰燼豹的烈火試煉，淬鍊星巡魔法球。',
        boss: '灰燼豹',
        rewardBeastId: 'ashen-jaguar',
      },
    ],
  },
  {
    id: 'celestial-sanctum',
    name: '天樞聖域',
    orbLevelRequired: 3,
    environment: '極光聖殿與星火神殿',
    summary: '極耀魔法球才能開啟的最終聖域，傳說王者沉眠之地。',
    chapters: [
      {
        id: 'celestial-1',
        name: '流風山脈',
        description: '與颶風麒麟並肩穿越亂流。',
        boss: '颶風麒麟',
        rewardBeastId: 'gale-kirin',
      },
      {
        id: 'celestial-2',
        name: '深潮裂谷',
        description: '下降至深潮裂谷，啟動潮汐巨靈。',
        boss: '潮汐巨靈',
        rewardBeastId: 'tidal-leviathan',
      },
      {
        id: 'celestial-3',
        name: '極光謎題',
        description: '破解極光斯芬克斯的三重謎題。',
        boss: '極光斯芬克斯',
        rewardBeastId: 'aurora-sphinx',
      },
      {
        id: 'celestial-4',
        name: '黑曜裂隙',
        description: '征服黑曜裂隙中的黑曜龍。',
        boss: '黑曜龍',
        rewardBeastId: 'obsidian-drake',
      },
      {
        id: 'celestial-5',
        name: '星火王座',
        description: '於星火王座與神話鳳凰正面對決。',
        boss: '神話鳳凰',
        rewardBeastId: 'mythic-phoenix',
      },
    ],
  },
];
